version: '3.8'

networks:
  linka-main:
    driver: bridge
  shops-us-east:
    driver: bridge
  shops-us-west:
    driver: bridge
  shops-eu:
    driver: bridge
  shops-asia:
    driver: bridge
  services-network:
    driver: bridge
  linka-network:
    driver: bridge

volumes:
  redis-data:
  postgres-data:
  node_modules:
  next_cache:

services:
  # Load Balancer
  nginx-lb:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - linka-main
      - shops-us-east
      - shops-us-west
      - shops-eu
      - shops-asia
      - services-network
    depends_on:
      - main-platform
    restart: unless-stopped

  # Main Platform
  main-platform:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - linka-main
      - services-network
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 2

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    networks:
      - linka-main
    restart: unless-stopped

  # Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: linka_platform
      POSTGRES_USER: linka_user
      POSTGRES_PASSWORD: linka_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - linka-main
    restart: unless-stopped

  # ===== SHOP CLUSTERS BY LOCATION =====
  
  # US East Coast Shops
  shop-us-east-1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3001
      - NODE_ENV=production
      - SHOP_REGION=us-east
      - SHOP_ID=us-east-1
      - REDIS_URL=redis://redis:6379
    networks:
      - shops-us-east
      - linka-main
    restart: unless-stopped

  shop-us-east-2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3001
      - NODE_ENV=production
      - SHOP_REGION=us-east
      - SHOP_ID=us-east-2
      - REDIS_URL=redis://redis:6379
    networks:
      - shops-us-east
      - linka-main
    restart: unless-stopped

  # US West Coast Shops
  shop-us-west-1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3002
      - NODE_ENV=production
      - SHOP_REGION=us-west
      - SHOP_ID=us-west-1
      - REDIS_URL=redis://redis:6379
    networks:
      - shops-us-west
      - linka-main
    restart: unless-stopped

  shop-us-west-2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3002
      - NODE_ENV=production
      - SHOP_REGION=us-west
      - SHOP_ID=us-west-2
      - REDIS_URL=redis://redis:6379
    networks:
      - shops-us-west
      - linka-main
    restart: unless-stopped

  # European Shops
  shop-eu-1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3003
      - NODE_ENV=production
      - SHOP_REGION=eu
      - SHOP_ID=eu-1
      - REDIS_URL=redis://redis:6379
    networks:
      - shops-eu
      - linka-main
    restart: unless-stopped

  shop-eu-2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3003
      - NODE_ENV=production
      - SHOP_REGION=eu
      - SHOP_ID=eu-2
      - REDIS_URL=redis://redis:6379
    networks:
      - shops-eu
      - linka-main
    restart: unless-stopped

  # Asian Shops
  shop-asia-1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3004
      - NODE_ENV=production
      - SHOP_REGION=asia
      - SHOP_ID=asia-1
      - REDIS_URL=redis://redis:6379
    networks:
      - shops-asia
      - linka-main
    restart: unless-stopped

  shop-asia-2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3004
      - NODE_ENV=production
      - SHOP_REGION=asia
      - SHOP_ID=asia-2
      - REDIS_URL=redis://redis:6379
    networks:
      - shops-asia
      - linka-main
    restart: unless-stopped

  # ===== INDUSTRY/SERVICE CLUSTERS =====

  # E-commerce Industry Cluster
  ecommerce-service:
    build:
      context: ./Services/E-com
      dockerfile: ../../Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SERVICE_TYPE=ecommerce
    networks:
      - services-network
      - linka-main
    restart: unless-stopped

  # E-learning Industry Cluster
  elearning-service:
    build:
      context: ./Services/E-Learning
      dockerfile: ../../Dockerfile
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SERVICE_TYPE=elearning
    networks:
      - services-network
      - linka-main
    restart: unless-stopped

  # Food Delivery Industry Cluster
  fooddelivery-service:
    build:
      context: ./Services/Food-Delivery
      dockerfile: ../../Dockerfile
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SERVICE_TYPE=fooddelivery
    networks:
      - services-network
      - linka-main
    restart: unless-stopped

  # Healthcare Industry Cluster
  healthcare-service:
    build:
      context: ./Services/Healthcare
      dockerfile: ../../Dockerfile
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SERVICE_TYPE=healthcare
    networks:
      - services-network
      - linka-main
    restart: unless-stopped

  # Travel & Tourism Industry Cluster
  travel-service:
    build:
      context: ./Services/Travel_&_Tourism
      dockerfile: ../../Dockerfile
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SERVICE_TYPE=travel
    networks:
      - services-network
      - linka-main
    restart: unless-stopped

  # Wholesale Industry Cluster
  wholesale-service:
    build:
      context: ./Services/Wholesale
      dockerfile: ../../Dockerfile
    ports:
      - "3006:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SERVICE_TYPE=wholesale
    networks:
      - services-network
      - linka-main
    restart: unless-stopped

  # ===== MONITORING & OBSERVABILITY =====
  
  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - linka-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  ecom:
    build:
      context: ./Services/E-com
      dockerfile: ../../Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
    volumes:
      - ./Services/E-com:/app
      - /app/node_modules
      - /app/.next
    networks:
      - linka-network
    restart: unless-stopped

  elearning:
    build:
      context: ./Services/E-Learning
      dockerfile: ../../Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NODE_ENV=development
    volumes:
      - ./Services/E-Learning:/app
      - /app/node_modules
      - /app/.next
    networks:
      - linka-network
    restart: unless-stopped

  fooddelivery:
    build:
      context: ./Services/Food-Delivery
      dockerfile: ../../Dockerfile
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - NODE_ENV=development
    volumes:
      - ./Services/Food-Delivery:/app
      - /app/node_modules
      - /app/.next
    networks:
      - linka-network
    restart: unless-stopped

  healthcare:
    build:
      context: ./Services/Healthcare
      dockerfile: ../../Dockerfile
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - NODE_ENV=development
    volumes:
      - ./Services/Healthcare:/app
      - /app/node_modules
      - /app/.next
    networks:
      - linka-network
    restart: unless-stopped

  travel_and_tourism:
    build:
      context: ./Services/Travel_&_Tourism
      dockerfile: ../../Dockerfile
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - NODE_ENV=development
    volumes:
      - ./Services/Travel_&_Tourism:/app
      - /app/node_modules
      - /app/.next
    networks:
      - linka-network
    restart: unless-stopped

  wholesale:
    build:
      context: ./Services/Wholesale
      dockerfile: ../../Dockerfile
    ports:
      - "3006:3006"
    environment:
      - PORT=3006
      - NODE_ENV=development
    volumes:
      - ./Services/Wholesale:/app
      - /app/node_modules
      - /app/.next
    networks:
      - linka-network
    restart: unless-stopped
