version: '3.8'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
