apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: gcr.io/linka-ecommerce-prod/my-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ENV_VAR
          valueFrom:
            configMapKeyRef:
              name: my-app-config
              key: APP_ENV
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: my-app-secret
              key: SECRET_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
